/* BEGIN carrier-brand-names — gen: node gen-carrier-css.mjs */
export const CARRIER_BRAND_NAMES = [
  "United Airlines",
  "Delta Air Lines",
  "American Airlines",
  "Jetblue Airways",
  "Spirit Airlines",
  "Frontier Airlines",
  "Southwest Airlines",
  "Alaska Airlines",
  "Air Canada",
  "British Airways",
  "Air France",
  "Lufthansa",
  "Emirates",
  "Virgin Atlantic",
  "Singapore Airlines",
  "Turkish Airlines",
  "Qatar Airways",
  "Etihad Airways",
  "KLM",
  "Swiss International Air Lines",
  "Air India",
  "Avianca",
  "Aeroméxico",
  "LATAM Airlines",
  "Copa Airlines",
  "All Nippon Airways (ANA)",
  "Japan Airlines",
  "Korean Air",
  "Asiana Airlines",
  "Cathay Pacific",
  "EVA Air",
  "Air China",
  "Qantas",
  "Air New Zealand",
  "SAS",
  "Finnair",
  "Icelandair",
  "Aer Lingus",
  "TAP Air Portugal",
  "Iberia",
  "ITA Airways",
  "Austrian Airlines",
  "Brussels Airlines",
  "LOT Polish Airlines",
  "El Al",
  "Egyptair",
  "Royal Air Maroc",
  "Ethiopian Airlines",
  "Porter Airlines",
  "Breeze Airways",
];
/* END carrier-brand-names */
